# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bank.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(961, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 941, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.branchTableView = QtWidgets.QTableView(self.tab)
        self.branchTableView.setGeometry(QtCore.QRect(10, 10, 661, 341))
        self.branchTableView.setObjectName("branchTableView")
        self.branchEditGroupBox = QtWidgets.QGroupBox(self.tab)
        self.branchEditGroupBox.setGeometry(QtCore.QRect(680, 10, 241, 341))
        self.branchEditGroupBox.setObjectName("branchEditGroupBox")
        self.branchIDLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchIDLabel.setGeometry(QtCore.QRect(20, 75, 54, 12))
        self.branchIDLabel.setObjectName("branchIDLabel")
        self.branchIDLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchIDLineEdit.setEnabled(False)
        self.branchIDLineEdit.setGeometry(QtCore.QRect(100, 70, 121, 21))
        self.branchIDLineEdit.setObjectName("branchIDLineEdit")
        self.saveBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.saveBranchPushButton.setGeometry(QtCore.QRect(150, 300, 75, 23))
        self.saveBranchPushButton.setObjectName("saveBranchPushButton")
        self.editBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.editBranchPushButton.setGeometry(QtCore.QRect(90, 20, 61, 23))
        self.editBranchPushButton.setObjectName("editBranchPushButton")
        self.abortBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.abortBranchPushButton.setGeometry(QtCore.QRect(50, 300, 75, 23))
        self.abortBranchPushButton.setObjectName("abortBranchPushButton")
        self.addBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.addBranchPushButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.addBranchPushButton.setObjectName("addBranchPushButton")
        self.deleteBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.deleteBranchPushButton.setGeometry(QtCore.QRect(170, 20, 61, 23))
        self.deleteBranchPushButton.setObjectName("deleteBranchPushButton")
        self.branchAssetsLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchAssetsLabel.setGeometry(QtCore.QRect(20, 230, 54, 12))
        self.branchAssetsLabel.setObjectName("branchAssetsLabel")
        self.branchAsertLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchAsertLineEdit.setEnabled(False)
        self.branchAsertLineEdit.setGeometry(QtCore.QRect(20, 250, 201, 20))
        self.branchAsertLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.branchAsertLineEdit.setObjectName("branchAsertLineEdit")
        self.branchNameLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchNameLineEdit.setEnabled(False)
        self.branchNameLineEdit.setGeometry(QtCore.QRect(20, 140, 201, 20))
        self.branchNameLineEdit.setObjectName("branchNameLineEdit")
        self.branchNameLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchNameLabel.setGeometry(QtCore.QRect(20, 120, 54, 12))
        self.branchNameLabel.setObjectName("branchNameLabel")
        self.branchCityLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchCityLabel.setGeometry(QtCore.QRect(20, 195, 54, 12))
        self.branchCityLabel.setObjectName("branchCityLabel")
        self.branchCityLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchCityLineEdit.setEnabled(False)
        self.branchCityLineEdit.setGeometry(QtCore.QRect(100, 190, 121, 20))
        self.branchCityLineEdit.setObjectName("branchCityLineEdit")
        self.branchSearchGroupBox = QtWidgets.QGroupBox(self.tab)
        self.branchSearchGroupBox.setGeometry(QtCore.QRect(10, 360, 911, 211))
        self.branchSearchGroupBox.setObjectName("branchSearchGroupBox")
        self.branchSearchPushButton = QtWidgets.QPushButton(self.branchSearchGroupBox)
        self.branchSearchPushButton.setGeometry(QtCore.QRect(780, 160, 101, 31))
        self.branchSearchPushButton.setObjectName("branchSearchPushButton")
        self.branchSearchBranchIDCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchBranchIDCheckBox.setGeometry(QtCore.QRect(20, 75, 61, 16))
        self.branchSearchBranchIDCheckBox.setObjectName("branchSearchBranchIDCheckBox")
        self.branchSearchBranchIDLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchBranchIDLineEdit.setEnabled(False)
        self.branchSearchBranchIDLineEdit.setGeometry(QtCore.QRect(200, 70, 101, 20))
        self.branchSearchBranchIDLineEdit.setObjectName("branchSearchBranchIDLineEdit")
        self.branchSearchBranchIDComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchBranchIDComboBox.setEnabled(False)
        self.branchSearchBranchIDComboBox.setGeometry(QtCore.QRect(90, 70, 91, 22))
        self.branchSearchBranchIDComboBox.setObjectName("branchSearchBranchIDComboBox")
        self.branchSearchBranchIDComboBox.addItem("")
        self.branchSearchBranchIDComboBox.addItem("")
        self.branchSearchBranchIDComboBox.addItem("")
        self.branchSearchRangeLabel = QtWidgets.QLabel(self.branchSearchGroupBox)
        self.branchSearchRangeLabel.setGeometry(QtCore.QRect(30, 25, 36, 12))
        self.branchSearchRangeLabel.setObjectName("branchSearchRangeLabel")
        self.branchSearchRangeComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchRangeComboBox.setGeometry(QtCore.QRect(110, 20, 111, 22))
        self.branchSearchRangeComboBox.setObjectName("branchSearchRangeComboBox")
        self.branchSearchRangeComboBox.addItem("")
        self.branchSearchRangeComboBox.addItem("")
        self.branchSearchBranchNameCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchBranchNameCheckBox.setGeometry(QtCore.QRect(20, 115, 71, 16))
        self.branchSearchBranchNameCheckBox.setObjectName("branchSearchBranchNameCheckBox")
        self.branchSearchBranchNameComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchBranchNameComboBox.setEnabled(False)
        self.branchSearchBranchNameComboBox.setGeometry(QtCore.QRect(88, 110, 91, 22))
        self.branchSearchBranchNameComboBox.setObjectName("branchSearchBranchNameComboBox")
        self.branchSearchBranchNameComboBox.addItem("")
        self.branchSearchBranchNameComboBox.addItem("")
        self.branchSearchBranchNameComboBox.addItem("")
        self.branchSearchBranchNameLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchBranchNameLineEdit.setEnabled(False)
        self.branchSearchBranchNameLineEdit.setGeometry(QtCore.QRect(200, 110, 101, 20))
        self.branchSearchBranchNameLineEdit.setObjectName("branchSearchBranchNameLineEdit")
        self.branchSearchCityCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchCityCheckBox.setGeometry(QtCore.QRect(330, 115, 51, 16))
        self.branchSearchCityCheckBox.setObjectName("branchSearchCityCheckBox")
        self.branchSearchCityComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchCityComboBox.setEnabled(False)
        self.branchSearchCityComboBox.setGeometry(QtCore.QRect(388, 110, 91, 22))
        self.branchSearchCityComboBox.setObjectName("branchSearchCityComboBox")
        self.branchSearchCityComboBox.addItem("")
        self.branchSearchCityComboBox.addItem("")
        self.branchSearchCityComboBox.addItem("")
        self.branchSearchCityLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchCityLineEdit.setEnabled(False)
        self.branchSearchCityLineEdit.setGeometry(QtCore.QRect(500, 110, 101, 20))
        self.branchSearchCityLineEdit.setObjectName("branchSearchCityLineEdit")
        self.branchSearchAssetComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchAssetComboBox.setEnabled(False)
        self.branchSearchAssetComboBox.setGeometry(QtCore.QRect(388, 70, 91, 22))
        self.branchSearchAssetComboBox.setObjectName("branchSearchAssetComboBox")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchAssetCheckBox.setGeometry(QtCore.QRect(330, 75, 71, 16))
        self.branchSearchAssetCheckBox.setObjectName("branchSearchAssetCheckBox")
        self.branchSearchAssetLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchAssetLineEdit.setEnabled(False)
        self.branchSearchAssetLineEdit.setGeometry(QtCore.QRect(500, 70, 101, 20))
        self.branchSearchAssetLineEdit.setObjectName("branchSearchAssetLineEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.employeeTableView = QtWidgets.QTableView(self.tab_2)
        self.employeeTableView.setGeometry(QtCore.QRect(10, 10, 661, 361))
        self.employeeTableView.setObjectName("employeeTableView")
        self.employeeEditGroupBox = QtWidgets.QGroupBox(self.tab_2)
        self.employeeEditGroupBox.setGeometry(QtCore.QRect(680, 10, 241, 361))
        self.employeeEditGroupBox.setObjectName("employeeEditGroupBox")
        self.employeeIDLabel = QtWidgets.QLabel(self.employeeEditGroupBox)
        self.employeeIDLabel.setGeometry(QtCore.QRect(10, 60, 65, 12))
        self.employeeIDLabel.setObjectName("employeeIDLabel")
        self.employeeIDLineEdit = QtWidgets.QLineEdit(self.employeeEditGroupBox)
        self.employeeIDLineEdit.setEnabled(False)
        self.employeeIDLineEdit.setGeometry(QtCore.QRect(80, 60, 151, 21))
        self.employeeIDLineEdit.setText("")
        self.employeeIDLineEdit.setObjectName("employeeIDLineEdit")
        self.employeeSavePushButton = QtWidgets.QPushButton(self.employeeEditGroupBox)
        self.employeeSavePushButton.setGeometry(QtCore.QRect(160, 320, 75, 23))
        self.employeeSavePushButton.setObjectName("employeeSavePushButton")
        self.employeeAlterPushButton = QtWidgets.QPushButton(self.employeeEditGroupBox)
        self.employeeAlterPushButton.setGeometry(QtCore.QRect(90, 20, 61, 23))
        self.employeeAlterPushButton.setObjectName("employeeAlterPushButton")
        self.employeeAbortPushButton = QtWidgets.QPushButton(self.employeeEditGroupBox)
        self.employeeAbortPushButton.setGeometry(QtCore.QRect(60, 320, 75, 23))
        self.employeeAbortPushButton.setObjectName("employeeAbortPushButton")
        self.employeeAddPushButton = QtWidgets.QPushButton(self.employeeEditGroupBox)
        self.employeeAddPushButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.employeeAddPushButton.setObjectName("employeeAddPushButton")
        self.employeeDeletePushButton = QtWidgets.QPushButton(self.employeeEditGroupBox)
        self.employeeDeletePushButton.setGeometry(QtCore.QRect(170, 20, 61, 23))
        self.employeeDeletePushButton.setObjectName("employeeDeletePushButton")
        self.employeeNameLineEdit = QtWidgets.QLineEdit(self.employeeEditGroupBox)
        self.employeeNameLineEdit.setEnabled(False)
        self.employeeNameLineEdit.setGeometry(QtCore.QRect(80, 110, 151, 20))
        self.employeeNameLineEdit.setObjectName("employeeNameLineEdit")
        self.employeeNameLabel = QtWidgets.QLabel(self.employeeEditGroupBox)
        self.employeeNameLabel.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.employeeNameLabel.setObjectName("employeeNameLabel")
        self.employeeTeleLabel = QtWidgets.QLabel(self.employeeEditGroupBox)
        self.employeeTeleLabel.setGeometry(QtCore.QRect(10, 160, 36, 12))
        self.employeeTeleLabel.setObjectName("employeeTeleLabel")
        self.employeeTeleLineEdit = QtWidgets.QLineEdit(self.employeeEditGroupBox)
        self.employeeTeleLineEdit.setEnabled(False)
        self.employeeTeleLineEdit.setGeometry(QtCore.QRect(80, 160, 151, 20))
        self.employeeTeleLineEdit.setObjectName("employeeTeleLineEdit")
        self.employeeAddressLabel = QtWidgets.QLabel(self.employeeEditGroupBox)
        self.employeeAddressLabel.setGeometry(QtCore.QRect(10, 210, 36, 12))
        self.employeeAddressLabel.setObjectName("employeeAddressLabel")
        self.employeeAddressLineEdit = QtWidgets.QLineEdit(self.employeeEditGroupBox)
        self.employeeAddressLineEdit.setEnabled(False)
        self.employeeAddressLineEdit.setGeometry(QtCore.QRect(50, 210, 181, 20))
        self.employeeAddressLineEdit.setObjectName("employeeAddressLineEdit")
        self.employeeSDateLabel = QtWidgets.QLabel(self.employeeEditGroupBox)
        self.employeeSDateLabel.setGeometry(QtCore.QRect(10, 260, 84, 12))
        self.employeeSDateLabel.setObjectName("employeeSDateLabel")
        self.employeeSDateEdit = QtWidgets.QDateEdit(self.employeeEditGroupBox)
        self.employeeSDateEdit.setEnabled(False)
        self.employeeSDateEdit.setGeometry(QtCore.QRect(120, 260, 110, 22))
        self.employeeSDateEdit.setObjectName("employeeSDateEdit")
        self.employeeSearchGroupBox = QtWidgets.QGroupBox(self.tab_2)
        self.employeeSearchGroupBox.setGeometry(QtCore.QRect(10, 380, 911, 191))
        self.employeeSearchGroupBox.setObjectName("employeeSearchGroupBox")
        self.employeeSearchPushButton = QtWidgets.QPushButton(self.employeeSearchGroupBox)
        self.employeeSearchPushButton.setGeometry(QtCore.QRect(790, 140, 101, 31))
        self.employeeSearchPushButton.setObjectName("employeeSearchPushButton")
        self.employeeSearchIDCheckBox = QtWidgets.QCheckBox(self.employeeSearchGroupBox)
        self.employeeSearchIDCheckBox.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.employeeSearchIDCheckBox.setObjectName("employeeSearchIDCheckBox")
        self.employeeSearchIDLineEdit = QtWidgets.QLineEdit(self.employeeSearchGroupBox)
        self.employeeSearchIDLineEdit.setEnabled(False)
        self.employeeSearchIDLineEdit.setGeometry(QtCore.QRect(190, 40, 121, 20))
        self.employeeSearchIDLineEdit.setObjectName("employeeSearchIDLineEdit")
        self.employeeSearchIDComboBox = QtWidgets.QComboBox(self.employeeSearchGroupBox)
        self.employeeSearchIDComboBox.setEnabled(False)
        self.employeeSearchIDComboBox.setGeometry(QtCore.QRect(100, 40, 71, 22))
        self.employeeSearchIDComboBox.setObjectName("employeeSearchIDComboBox")
        self.employeeSearchIDComboBox.addItem("")
        self.employeeSearchIDComboBox.addItem("")
        self.employeeSearchIDComboBox.addItem("")
        self.employeeSearchNameCheckBox = QtWidgets.QCheckBox(self.employeeSearchGroupBox)
        self.employeeSearchNameCheckBox.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.employeeSearchNameCheckBox.setObjectName("employeeSearchNameCheckBox")
        self.employeeSearchNameComboBox = QtWidgets.QComboBox(self.employeeSearchGroupBox)
        self.employeeSearchNameComboBox.setEnabled(False)
        self.employeeSearchNameComboBox.setGeometry(QtCore.QRect(100, 90, 71, 22))
        self.employeeSearchNameComboBox.setObjectName("employeeSearchNameComboBox")
        self.employeeSearchNameComboBox.addItem("")
        self.employeeSearchNameComboBox.addItem("")
        self.employeeSearchNameComboBox.addItem("")
        self.employeeSearchNameLineEdit = QtWidgets.QLineEdit(self.employeeSearchGroupBox)
        self.employeeSearchNameLineEdit.setEnabled(False)
        self.employeeSearchNameLineEdit.setGeometry(QtCore.QRect(190, 90, 121, 20))
        self.employeeSearchNameLineEdit.setObjectName("employeeSearchNameLineEdit")
        self.employeeSearchInfoCheckBox = QtWidgets.QCheckBox(self.employeeSearchGroupBox)
        self.employeeSearchInfoCheckBox.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.employeeSearchInfoCheckBox.setObjectName("employeeSearchInfoCheckBox")
        self.employeeSearchInfoComboBox = QtWidgets.QComboBox(self.employeeSearchGroupBox)
        self.employeeSearchInfoComboBox.setEnabled(False)
        self.employeeSearchInfoComboBox.setGeometry(QtCore.QRect(100, 140, 71, 22))
        self.employeeSearchInfoComboBox.setObjectName("employeeSearchInfoComboBox")
        self.employeeSearchInfoComboBox.addItem("")
        self.employeeSearchInfoLineEdit = QtWidgets.QLineEdit(self.employeeSearchGroupBox)
        self.employeeSearchInfoLineEdit.setEnabled(False)
        self.employeeSearchInfoLineEdit.setGeometry(QtCore.QRect(190, 140, 121, 20))
        self.employeeSearchInfoLineEdit.setObjectName("employeeSearchInfoLineEdit")
        self.employeeSearchSDateCheckBox = QtWidgets.QCheckBox(self.employeeSearchGroupBox)
        self.employeeSearchSDateCheckBox.setGeometry(QtCore.QRect(380, 40, 95, 16))
        self.employeeSearchSDateCheckBox.setObjectName("employeeSearchSDateCheckBox")
        self.employeeSearchSDateComboBox = QtWidgets.QComboBox(self.employeeSearchGroupBox)
        self.employeeSearchSDateComboBox.setEnabled(False)
        self.employeeSearchSDateComboBox.setGeometry(QtCore.QRect(490, 40, 71, 22))
        self.employeeSearchSDateComboBox.setObjectName("employeeSearchSDateComboBox")
        self.employeeSearchSDateComboBox.addItem("")
        self.employeeSearchSDateComboBox.addItem("")
        self.employeeSearchSDateComboBox.addItem("")
        self.employeeSearchSDateComboBox.addItem("")
        self.employeeSearchSDateComboBox.addItem("")
        self.employeeSearchSDateComboBox.addItem("")
        self.employeeSearchSDateEdit = QtWidgets.QDateEdit(self.employeeSearchGroupBox)
        self.employeeSearchSDateEdit.setEnabled(False)
        self.employeeSearchSDateEdit.setGeometry(QtCore.QRect(580, 40, 110, 22))
        self.employeeSearchSDateEdit.setObjectName("employeeSearchSDateEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.customerTableView = QtWidgets.QTableView(self.tab_3)
        self.customerTableView.setGeometry(QtCore.QRect(10, 10, 661, 361))
        self.customerTableView.setObjectName("customerTableView")
        self.customerEditGroupBox = QtWidgets.QGroupBox(self.tab_3)
        self.customerEditGroupBox.setGeometry(QtCore.QRect(680, 10, 241, 361))
        self.customerEditGroupBox.setObjectName("customerEditGroupBox")
        self.customerIDLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.customerIDLabel.setGeometry(QtCore.QRect(10, 55, 65, 12))
        self.customerIDLabel.setObjectName("customerIDLabel")
        self.customerIDLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.customerIDLineEdit.setEnabled(False)
        self.customerIDLineEdit.setGeometry(QtCore.QRect(80, 50, 151, 21))
        self.customerIDLineEdit.setText("")
        self.customerIDLineEdit.setObjectName("customerIDLineEdit")
        self.customerSavePushButton = QtWidgets.QPushButton(self.customerEditGroupBox)
        self.customerSavePushButton.setGeometry(QtCore.QRect(160, 320, 75, 23))
        self.customerSavePushButton.setObjectName("customerSavePushButton")
        self.customerAlterPushButton = QtWidgets.QPushButton(self.customerEditGroupBox)
        self.customerAlterPushButton.setGeometry(QtCore.QRect(90, 20, 61, 23))
        self.customerAlterPushButton.setObjectName("customerAlterPushButton")
        self.customerAbortPushButton = QtWidgets.QPushButton(self.customerEditGroupBox)
        self.customerAbortPushButton.setGeometry(QtCore.QRect(60, 320, 75, 23))
        self.customerAbortPushButton.setObjectName("customerAbortPushButton")
        self.customerAddPushButton = QtWidgets.QPushButton(self.customerEditGroupBox)
        self.customerAddPushButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.customerAddPushButton.setObjectName("customerAddPushButton")
        self.customerDeletePushButton = QtWidgets.QPushButton(self.customerEditGroupBox)
        self.customerDeletePushButton.setGeometry(QtCore.QRect(170, 20, 61, 23))
        self.customerDeletePushButton.setObjectName("customerDeletePushButton")
        self.customerNameLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.customerNameLineEdit.setEnabled(False)
        self.customerNameLineEdit.setGeometry(QtCore.QRect(80, 80, 151, 20))
        self.customerNameLineEdit.setObjectName("customerNameLineEdit")
        self.customerNameLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.customerNameLabel.setGeometry(QtCore.QRect(10, 85, 54, 12))
        self.customerNameLabel.setObjectName("customerNameLabel")
        self.customerTeleLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.customerTeleLabel.setGeometry(QtCore.QRect(10, 115, 36, 12))
        self.customerTeleLabel.setObjectName("customerTeleLabel")
        self.customerTeleLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.customerTeleLineEdit.setEnabled(False)
        self.customerTeleLineEdit.setGeometry(QtCore.QRect(80, 110, 151, 20))
        self.customerTeleLineEdit.setObjectName("customerTeleLineEdit")
        self.customerAddressLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.customerAddressLabel.setGeometry(QtCore.QRect(10, 145, 36, 12))
        self.customerAddressLabel.setObjectName("customerAddressLabel")
        self.customerAddressLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.customerAddressLineEdit.setEnabled(False)
        self.customerAddressLineEdit.setGeometry(QtCore.QRect(50, 140, 181, 20))
        self.customerAddressLineEdit.setObjectName("customerAddressLineEdit")
        self.contactNameLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.contactNameLabel.setGeometry(QtCore.QRect(10, 175, 72, 12))
        self.contactNameLabel.setObjectName("contactNameLabel")
        self.contactTeleLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.contactTeleLabel.setGeometry(QtCore.QRect(10, 205, 72, 12))
        self.contactTeleLabel.setObjectName("contactTeleLabel")
        self.contactEmailLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.contactEmailLabel.setGeometry(QtCore.QRect(10, 230, 120, 12))
        self.contactEmailLabel.setObjectName("contactEmailLabel")
        self.contactRelationshipLabel = QtWidgets.QLabel(self.customerEditGroupBox)
        self.contactRelationshipLabel.setGeometry(QtCore.QRect(10, 280, 72, 12))
        self.contactRelationshipLabel.setObjectName("contactRelationshipLabel")
        self.contactNameLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.contactNameLineEdit.setEnabled(False)
        self.contactNameLineEdit.setGeometry(QtCore.QRect(90, 170, 141, 21))
        self.contactNameLineEdit.setText("")
        self.contactNameLineEdit.setObjectName("contactNameLineEdit")
        self.contactTeleLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.contactTeleLineEdit.setEnabled(False)
        self.contactTeleLineEdit.setGeometry(QtCore.QRect(90, 200, 141, 21))
        self.contactTeleLineEdit.setText("")
        self.contactTeleLineEdit.setObjectName("contactTeleLineEdit")
        self.contactEmailLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.contactEmailLineEdit.setEnabled(False)
        self.contactEmailLineEdit.setGeometry(QtCore.QRect(10, 250, 221, 21))
        self.contactEmailLineEdit.setText("")
        self.contactEmailLineEdit.setObjectName("contactEmailLineEdit")
        self.contactRelationshipLineEdit = QtWidgets.QLineEdit(self.customerEditGroupBox)
        self.contactRelationshipLineEdit.setEnabled(False)
        self.contactRelationshipLineEdit.setGeometry(QtCore.QRect(100, 280, 131, 21))
        self.contactRelationshipLineEdit.setText("")
        self.contactRelationshipLineEdit.setObjectName("contactRelationshipLineEdit")
        self.customerSearchGroupBox = QtWidgets.QGroupBox(self.tab_3)
        self.customerSearchGroupBox.setGeometry(QtCore.QRect(10, 380, 911, 191))
        self.customerSearchGroupBox.setObjectName("customerSearchGroupBox")
        self.customerSearchPushButton = QtWidgets.QPushButton(self.customerSearchGroupBox)
        self.customerSearchPushButton.setGeometry(QtCore.QRect(790, 140, 101, 31))
        self.customerSearchPushButton.setObjectName("customerSearchPushButton")
        self.customerSearchCustomerIDCheckBox = QtWidgets.QCheckBox(self.customerSearchGroupBox)
        self.customerSearchCustomerIDCheckBox.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.customerSearchCustomerIDCheckBox.setObjectName("customerSearchCustomerIDCheckBox")
        self.customerSearchCustomerIDLineEdit = QtWidgets.QLineEdit(self.customerSearchGroupBox)
        self.customerSearchCustomerIDLineEdit.setEnabled(False)
        self.customerSearchCustomerIDLineEdit.setGeometry(QtCore.QRect(200, 40, 101, 20))
        self.customerSearchCustomerIDLineEdit.setObjectName("customerSearchCustomerIDLineEdit")
        self.customerSearchCustomerIDComboBox = QtWidgets.QComboBox(self.customerSearchGroupBox)
        self.customerSearchCustomerIDComboBox.setEnabled(False)
        self.customerSearchCustomerIDComboBox.setGeometry(QtCore.QRect(110, 40, 71, 22))
        self.customerSearchCustomerIDComboBox.setObjectName("customerSearchCustomerIDComboBox")
        self.customerSearchCustomerIDComboBox.addItem("")
        self.customerSearchCustomerIDComboBox.addItem("")
        self.customerSearchCustomerIDComboBox.addItem("")
        self.customerSearchCustomerNameCheckBox = QtWidgets.QCheckBox(self.customerSearchGroupBox)
        self.customerSearchCustomerNameCheckBox.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.customerSearchCustomerNameCheckBox.setObjectName("customerSearchCustomerNameCheckBox")
        self.customerSearchCustomerNameComboBox = QtWidgets.QComboBox(self.customerSearchGroupBox)
        self.customerSearchCustomerNameComboBox.setEnabled(False)
        self.customerSearchCustomerNameComboBox.setGeometry(QtCore.QRect(110, 90, 71, 22))
        self.customerSearchCustomerNameComboBox.setObjectName("customerSearchCustomerNameComboBox")
        self.customerSearchCustomerNameComboBox.addItem("")
        self.customerSearchCustomerNameComboBox.addItem("")
        self.customerSearchCustomerNameComboBox.addItem("")
        self.customerSearchCustomerNameLineEdit = QtWidgets.QLineEdit(self.customerSearchGroupBox)
        self.customerSearchCustomerNameLineEdit.setEnabled(False)
        self.customerSearchCustomerNameLineEdit.setGeometry(QtCore.QRect(200, 90, 101, 20))
        self.customerSearchCustomerNameLineEdit.setObjectName("customerSearchCustomerNameLineEdit")
        self.customerSearchOtherInfoCheckBox = QtWidgets.QCheckBox(self.customerSearchGroupBox)
        self.customerSearchOtherInfoCheckBox.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.customerSearchOtherInfoCheckBox.setObjectName("customerSearchOtherInfoCheckBox")
        self.customerSearchOtherInfoComboBox = QtWidgets.QComboBox(self.customerSearchGroupBox)
        self.customerSearchOtherInfoComboBox.setEnabled(False)
        self.customerSearchOtherInfoComboBox.setGeometry(QtCore.QRect(110, 140, 71, 22))
        self.customerSearchOtherInfoComboBox.setObjectName("customerSearchOtherInfoComboBox")
        self.customerSearchOtherInfoComboBox.addItem("")
        self.customerSearchOtherInfoLineEdit = QtWidgets.QLineEdit(self.customerSearchGroupBox)
        self.customerSearchOtherInfoLineEdit.setEnabled(False)
        self.customerSearchOtherInfoLineEdit.setGeometry(QtCore.QRect(200, 140, 101, 20))
        self.customerSearchOtherInfoLineEdit.setObjectName("customerSearchOtherInfoLineEdit")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.accountTableView = QtWidgets.QTableView(self.tab_4)
        self.accountTableView.setEnabled(True)
        self.accountTableView.setGeometry(QtCore.QRect(10, 10, 661, 471))
        self.accountTableView.setObjectName("accountTableView")
        self.accountEditGroupBox = QtWidgets.QGroupBox(self.tab_4)
        self.accountEditGroupBox.setGeometry(QtCore.QRect(680, 10, 241, 471))
        self.accountEditGroupBox.setObjectName("accountEditGroupBox")
        self.accountIDLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountIDLabel.setGeometry(QtCore.QRect(10, 55, 48, 12))
        self.accountIDLabel.setObjectName("accountIDLabel")
        self.accountSavePushButton = QtWidgets.QPushButton(self.accountEditGroupBox)
        self.accountSavePushButton.setGeometry(QtCore.QRect(160, 440, 75, 23))
        self.accountSavePushButton.setObjectName("accountSavePushButton")
        self.accountAlterPushButton = QtWidgets.QPushButton(self.accountEditGroupBox)
        self.accountAlterPushButton.setGeometry(QtCore.QRect(90, 20, 61, 23))
        self.accountAlterPushButton.setObjectName("accountAlterPushButton")
        self.accountAbortPushButton = QtWidgets.QPushButton(self.accountEditGroupBox)
        self.accountAbortPushButton.setGeometry(QtCore.QRect(60, 440, 75, 23))
        self.accountAbortPushButton.setObjectName("accountAbortPushButton")
        self.accountAddPushButton = QtWidgets.QPushButton(self.accountEditGroupBox)
        self.accountAddPushButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.accountAddPushButton.setObjectName("accountAddPushButton")
        self.accountDeletePushButton = QtWidgets.QPushButton(self.accountEditGroupBox)
        self.accountDeletePushButton.setGeometry(QtCore.QRect(170, 20, 61, 23))
        self.accountDeletePushButton.setObjectName("accountDeletePushButton")
        self.accountCIDLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountCIDLineEdit.setEnabled(False)
        self.accountCIDLineEdit.setGeometry(QtCore.QRect(100, 160, 131, 20))
        self.accountCIDLineEdit.setObjectName("accountCIDLineEdit")
        self.accountCIDLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountCIDLabel.setGeometry(QtCore.QRect(10, 160, 54, 12))
        self.accountCIDLabel.setObjectName("accountCIDLabel")
        self.accountBIDLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountBIDLabel.setGeometry(QtCore.QRect(10, 115, 48, 12))
        self.accountBIDLabel.setObjectName("accountBIDLabel")
        self.accountBIDLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountBIDLineEdit.setEnabled(False)
        self.accountBIDLineEdit.setGeometry(QtCore.QRect(100, 110, 131, 20))
        self.accountBIDLineEdit.setObjectName("accountBIDLineEdit")
        self.accountCNLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountCNLabel.setEnabled(True)
        self.accountCNLabel.setGeometry(QtCore.QRect(10, 190, 36, 12))
        self.accountCNLabel.setObjectName("accountCNLabel")
        self.accountBalanceLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountBalanceLabel.setGeometry(QtCore.QRect(10, 210, 41, 16))
        self.accountBalanceLabel.setObjectName("accountBalanceLabel")
        self.accountIRateLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountIRateLabel.setGeometry(QtCore.QRect(10, 270, 72, 12))
        self.accountIRateLabel.setObjectName("accountIRateLabel")
        self.accountODateLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountODateLabel.setGeometry(QtCore.QRect(10, 300, 60, 12))
        self.accountODateLabel.setObjectName("accountODateLabel")
        self.accountLDateLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountLDateLabel.setGeometry(QtCore.QRect(10, 330, 84, 12))
        self.accountLDateLabel.setObjectName("accountLDateLabel")
        self.accountBalanceLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountBalanceLineEdit.setEnabled(False)
        self.accountBalanceLineEdit.setGeometry(QtCore.QRect(100, 210, 131, 21))
        self.accountBalanceLineEdit.setText("")
        self.accountBalanceLineEdit.setObjectName("accountBalanceLineEdit")
        self.accountIRateLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountIRateLineEdit.setEnabled(False)
        self.accountIRateLineEdit.setGeometry(QtCore.QRect(100, 270, 131, 21))
        self.accountIRateLineEdit.setText("")
        self.accountIRateLineEdit.setObjectName("accountIRateLineEdit")
        self.accountIDLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountIDLineEdit.setEnabled(False)
        self.accountIDLineEdit.setGeometry(QtCore.QRect(100, 50, 131, 20))
        self.accountIDLineEdit.setObjectName("accountIDLineEdit")
        self.accountCreditLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountCreditLineEdit.setEnabled(False)
        self.accountCreditLineEdit.setGeometry(QtCore.QRect(100, 240, 131, 21))
        self.accountCreditLineEdit.setText("")
        self.accountCreditLineEdit.setObjectName("accountCreditLineEdit")
        self.accountBalanceCreditLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountBalanceCreditLabel.setEnabled(True)
        self.accountBalanceCreditLabel.setGeometry(QtCore.QRect(10, 240, 41, 16))
        self.accountBalanceCreditLabel.setObjectName("accountBalanceCreditLabel")
        self.accountTypeLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountTypeLabel.setGeometry(QtCore.QRect(10, 85, 60, 12))
        self.accountTypeLabel.setObjectName("accountTypeLabel")
        self.accountTypeComboBox = QtWidgets.QComboBox(self.accountEditGroupBox)
        self.accountTypeComboBox.setEnabled(False)
        self.accountTypeComboBox.setGeometry(QtCore.QRect(100, 80, 131, 22))
        self.accountTypeComboBox.setObjectName("accountTypeComboBox")
        self.accountTypeComboBox.addItem("")
        self.accountTypeComboBox.addItem("")
        self.accountODateEdit = QtWidgets.QDateEdit(self.accountEditGroupBox)
        self.accountODateEdit.setEnabled(False)
        self.accountODateEdit.setGeometry(QtCore.QRect(100, 300, 131, 22))
        self.accountODateEdit.setObjectName("accountODateEdit")
        self.accountLastDateEdit = QtWidgets.QDateEdit(self.accountEditGroupBox)
        self.accountLastDateEdit.setEnabled(False)
        self.accountLastDateEdit.setGeometry(QtCore.QRect(100, 330, 131, 22))
        self.accountLastDateEdit.setObjectName("accountLastDateEdit")
        self.accountEIDLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountEIDLabel.setGeometry(QtCore.QRect(10, 360, 72, 12))
        self.accountEIDLabel.setObjectName("accountEIDLabel")
        self.accountEIDLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountEIDLineEdit.setEnabled(False)
        self.accountEIDLineEdit.setGeometry(QtCore.QRect(100, 360, 131, 21))
        self.accountEIDLineEdit.setText("")
        self.accountEIDLineEdit.setObjectName("accountEIDLineEdit")
        self.accountENLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountENLabel.setEnabled(True)
        self.accountENLabel.setGeometry(QtCore.QRect(10, 390, 72, 12))
        self.accountENLabel.setObjectName("accountENLabel")
        self.accountCNYLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountCNYLabel.setGeometry(QtCore.QRect(10, 410, 72, 12))
        self.accountCNYLabel.setObjectName("accountCNYLabel")
        self.accountCNYLineEdit = QtWidgets.QLineEdit(self.accountEditGroupBox)
        self.accountCNYLineEdit.setEnabled(False)
        self.accountCNYLineEdit.setGeometry(QtCore.QRect(100, 410, 131, 21))
        self.accountCNYLineEdit.setText("")
        self.accountCNYLineEdit.setObjectName("accountCNYLineEdit")
        self.accountBNLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountBNLabel.setEnabled(True)
        self.accountBNLabel.setGeometry(QtCore.QRect(10, 140, 48, 12))
        self.accountBNLabel.setObjectName("accountBNLabel")
        self.accountBNameLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountBNameLabel.setGeometry(QtCore.QRect(100, 140, 220, 12))
        self.accountBNameLabel.setText("")
        self.accountBNameLabel.setObjectName("accountBNameLabel")
        self.accountCNameLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountCNameLabel.setEnabled(True)
        self.accountCNameLabel.setGeometry(QtCore.QRect(100, 190, 220, 12))
        self.accountCNameLabel.setText("")
        self.accountCNameLabel.setObjectName("accountCNameLabel")
        self.accountENameLabel = QtWidgets.QLabel(self.accountEditGroupBox)
        self.accountENameLabel.setEnabled(True)
        self.accountENameLabel.setGeometry(QtCore.QRect(100, 390, 220, 12))
        self.accountENameLabel.setText("")
        self.accountENameLabel.setObjectName("accountENameLabel")
        self.accountSearchGroupBox = QtWidgets.QGroupBox(self.tab_4)
        self.accountSearchGroupBox.setGeometry(QtCore.QRect(10, 490, 911, 91))
        self.accountSearchGroupBox.setObjectName("accountSearchGroupBox")
        self.accountSearchPushButton = QtWidgets.QPushButton(self.accountSearchGroupBox)
        self.accountSearchPushButton.setGeometry(QtCore.QRect(740, 40, 101, 31))
        self.accountSearchPushButton.setObjectName("accountSearchPushButton")
        self.accountSearchRangeLabel = QtWidgets.QLabel(self.accountSearchGroupBox)
        self.accountSearchRangeLabel.setGeometry(QtCore.QRect(50, 20, 36, 12))
        self.accountSearchRangeLabel.setObjectName("accountSearchRangeLabel")
        self.accountSearchRangeComboBox = QtWidgets.QComboBox(self.accountSearchGroupBox)
        self.accountSearchRangeComboBox.setGeometry(QtCore.QRect(140, 20, 111, 22))
        self.accountSearchRangeComboBox.setObjectName("accountSearchRangeComboBox")
        self.accountSearchRangeComboBox.addItem("")
        self.accountSearchRangeComboBox.addItem("")
        self.accountSearchCheckBox = QtWidgets.QCheckBox(self.accountSearchGroupBox)
        self.accountSearchCheckBox.setGeometry(QtCore.QRect(50, 60, 59, 16))
        self.accountSearchCheckBox.setObjectName("accountSearchCheckBox")
        self.accountSearchOpComboBox = QtWidgets.QComboBox(self.accountSearchGroupBox)
        self.accountSearchOpComboBox.setEnabled(False)
        self.accountSearchOpComboBox.setGeometry(QtCore.QRect(280, 60, 91, 22))
        self.accountSearchOpComboBox.setObjectName("accountSearchOpComboBox")
        self.accountSearchOpComboBox.addItem("")
        self.accountSearchOpComboBox.addItem("")
        self.accountSearchOpComboBox.addItem("")
        self.accountSearchLineEdit = QtWidgets.QLineEdit(self.accountSearchGroupBox)
        self.accountSearchLineEdit.setEnabled(False)
        self.accountSearchLineEdit.setGeometry(QtCore.QRect(440, 60, 211, 20))
        self.accountSearchLineEdit.setObjectName("accountSearchLineEdit")
        self.accountSearchColComboBox = QtWidgets.QComboBox(self.accountSearchGroupBox)
        self.accountSearchColComboBox.setEnabled(False)
        self.accountSearchColComboBox.setGeometry(QtCore.QRect(140, 60, 91, 22))
        self.accountSearchColComboBox.setObjectName("accountSearchColComboBox")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.accountSearchColComboBox.addItem("")
        self.label = QtWidgets.QLabel(self.accountSearchGroupBox)
        self.label.setGeometry(QtCore.QRect(510, 20, 120, 12))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.loanTableView = QtWidgets.QTableView(self.tab_5)
        self.loanTableView.setGeometry(QtCore.QRect(10, 10, 671, 431))
        self.loanTableView.setObjectName("loanTableView")
        self.accountSearchGroupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.accountSearchGroupBox_2.setGeometry(QtCore.QRect(10, 450, 671, 121))
        self.accountSearchGroupBox_2.setObjectName("accountSearchGroupBox_2")
        self.accountSearchPushButton_2 = QtWidgets.QPushButton(self.accountSearchGroupBox_2)
        self.accountSearchPushButton_2.setGeometry(QtCore.QRect(550, 50, 101, 31))
        self.accountSearchPushButton_2.setObjectName("accountSearchPushButton_2")
        self.accountSearchRangeLabel_2 = QtWidgets.QLabel(self.accountSearchGroupBox_2)
        self.accountSearchRangeLabel_2.setGeometry(QtCore.QRect(30, 30, 36, 12))
        self.accountSearchRangeLabel_2.setObjectName("accountSearchRangeLabel_2")
        self.accountSearchRangeComboBox_2 = QtWidgets.QComboBox(self.accountSearchGroupBox_2)
        self.accountSearchRangeComboBox_2.setGeometry(QtCore.QRect(90, 30, 111, 22))
        self.accountSearchRangeComboBox_2.setObjectName("accountSearchRangeComboBox_2")
        self.accountSearchRangeComboBox_2.addItem("")
        self.accountSearchRangeComboBox_2.addItem("")
        self.accountSearchCheckBox_2 = QtWidgets.QCheckBox(self.accountSearchGroupBox_2)
        self.accountSearchCheckBox_2.setGeometry(QtCore.QRect(20, 80, 59, 16))
        self.accountSearchCheckBox_2.setObjectName("accountSearchCheckBox_2")
        self.accountSearchOpComboBox_2 = QtWidgets.QComboBox(self.accountSearchGroupBox_2)
        self.accountSearchOpComboBox_2.setEnabled(False)
        self.accountSearchOpComboBox_2.setGeometry(QtCore.QRect(210, 80, 91, 22))
        self.accountSearchOpComboBox_2.setObjectName("accountSearchOpComboBox_2")
        self.accountSearchOpComboBox_2.addItem("")
        self.accountSearchOpComboBox_2.addItem("")
        self.accountSearchOpComboBox_2.addItem("")
        self.accountSearchLineEdit_2 = QtWidgets.QLineEdit(self.accountSearchGroupBox_2)
        self.accountSearchLineEdit_2.setEnabled(False)
        self.accountSearchLineEdit_2.setGeometry(QtCore.QRect(320, 80, 211, 20))
        self.accountSearchLineEdit_2.setObjectName("accountSearchLineEdit_2")
        self.accountSearchColComboBox_2 = QtWidgets.QComboBox(self.accountSearchGroupBox_2)
        self.accountSearchColComboBox_2.setEnabled(False)
        self.accountSearchColComboBox_2.setGeometry(QtCore.QRect(100, 80, 91, 22))
        self.accountSearchColComboBox_2.setObjectName("accountSearchColComboBox_2")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.accountSearchColComboBox_2.addItem("")
        self.label_2 = QtWidgets.QLabel(self.accountSearchGroupBox_2)
        self.label_2.setGeometry(QtCore.QRect(360, 100, 120, 12))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setGeometry(QtCore.QRect(690, 10, 231, 561))
        self.groupBox.setObjectName("groupBox")
        self.accountDeletePushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.accountDeletePushButton_2.setGeometry(QtCore.QRect(130, 30, 61, 23))
        self.accountDeletePushButton_2.setObjectName("accountDeletePushButton_2")
        self.accountAddPushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.accountAddPushButton_2.setGeometry(QtCore.QRect(40, 30, 61, 23))
        self.accountAddPushButton_2.setObjectName("accountAddPushButton_2")
        self.accountSavePushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.accountSavePushButton_2.setGeometry(QtCore.QRect(130, 510, 75, 23))
        self.accountSavePushButton_2.setObjectName("accountSavePushButton_2")
        self.accountAbortPushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.accountAbortPushButton_2.setGeometry(QtCore.QRect(30, 510, 75, 23))
        self.accountAbortPushButton_2.setObjectName("accountAbortPushButton_2")
        self.loanTableView_2 = QtWidgets.QTableView(self.groupBox)
        self.loanTableView_2.setGeometry(QtCore.QRect(20, 260, 201, 151))
        self.loanTableView_2.setObjectName("loanTableView_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 48, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 36, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 60, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 48, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 48, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 180, 60, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 200, 96, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 220, 36, 12))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 240, 60, 12))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 120, 48, 12))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(20, 420, 60, 12))
        self.label_13.setObjectName("label_13")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(20, 440, 121, 22))
        self.spinBox.setMaximum(10000)
        self.spinBox.setObjectName("spinBox")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "银行业务管理系统"))
        self.branchEditGroupBox.setTitle(_translate("MainWindow", "管理"))
        self.branchIDLabel.setText(_translate("MainWindow", "支行编号："))
        self.saveBranchPushButton.setText(_translate("MainWindow", "保存"))
        self.editBranchPushButton.setText(_translate("MainWindow", "修改"))
        self.abortBranchPushButton.setText(_translate("MainWindow", "放弃"))
        self.addBranchPushButton.setText(_translate("MainWindow", "添加"))
        self.deleteBranchPushButton.setText(_translate("MainWindow", "删除"))
        self.branchAssetsLabel.setText(_translate("MainWindow", "支行资产："))
        self.branchNameLabel.setText(_translate("MainWindow", "支行名："))
        self.branchCityLabel.setText(_translate("MainWindow", "城市："))
        self.branchSearchGroupBox.setTitle(_translate("MainWindow", "查找"))
        self.branchSearchPushButton.setText(_translate("MainWindow", "查找"))
        self.branchSearchBranchIDCheckBox.setText(_translate("MainWindow", "支行号"))
        self.branchSearchBranchIDComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.branchSearchBranchIDComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.branchSearchBranchIDComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.branchSearchRangeLabel.setText(_translate("MainWindow", "范围："))
        self.branchSearchRangeComboBox.setItemText(0, _translate("MainWindow", "全部"))
        self.branchSearchRangeComboBox.setItemText(1, _translate("MainWindow", "上一次结果"))
        self.branchSearchBranchNameCheckBox.setText(_translate("MainWindow", "支行名"))
        self.branchSearchBranchNameComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.branchSearchBranchNameComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.branchSearchBranchNameComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.branchSearchCityCheckBox.setText(_translate("MainWindow", "城市"))
        self.branchSearchCityComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.branchSearchCityComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.branchSearchCityComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.branchSearchAssetComboBox.setItemText(0, _translate("MainWindow", "大于"))
        self.branchSearchAssetComboBox.setItemText(1, _translate("MainWindow", "大于等于"))
        self.branchSearchAssetComboBox.setItemText(2, _translate("MainWindow", "等于"))
        self.branchSearchAssetComboBox.setItemText(3, _translate("MainWindow", "小于等于"))
        self.branchSearchAssetComboBox.setItemText(4, _translate("MainWindow", "小于"))
        self.branchSearchAssetComboBox.setItemText(5, _translate("MainWindow", "不等于"))
        self.branchSearchAssetCheckBox.setText(_translate("MainWindow", "资产"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "支行管理"))
        self.employeeEditGroupBox.setTitle(_translate("MainWindow", "管理"))
        self.employeeIDLabel.setText(_translate("MainWindow", "身份证号："))
        self.employeeSavePushButton.setText(_translate("MainWindow", "保存"))
        self.employeeAlterPushButton.setText(_translate("MainWindow", "修改"))
        self.employeeAbortPushButton.setText(_translate("MainWindow", "放弃"))
        self.employeeAddPushButton.setText(_translate("MainWindow", "添加"))
        self.employeeDeletePushButton.setText(_translate("MainWindow", "删除"))
        self.employeeNameLabel.setText(_translate("MainWindow", "姓名："))
        self.employeeTeleLabel.setText(_translate("MainWindow", "电话："))
        self.employeeAddressLabel.setText(_translate("MainWindow", "地址："))
        self.employeeSDateLabel.setText(_translate("MainWindow", "开始工作日期："))
        self.employeeSDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.employeeSearchGroupBox.setTitle(_translate("MainWindow", "查找"))
        self.employeeSearchPushButton.setText(_translate("MainWindow", "查找"))
        self.employeeSearchIDCheckBox.setText(_translate("MainWindow", "身份证号"))
        self.employeeSearchIDComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.employeeSearchIDComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.employeeSearchIDComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.employeeSearchNameCheckBox.setText(_translate("MainWindow", "姓名"))
        self.employeeSearchNameComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.employeeSearchNameComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.employeeSearchNameComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.employeeSearchInfoCheckBox.setText(_translate("MainWindow", "其他信息"))
        self.employeeSearchInfoComboBox.setCurrentText(_translate("MainWindow", "包含"))
        self.employeeSearchInfoComboBox.setItemText(0, _translate("MainWindow", "包含"))
        self.employeeSearchSDateCheckBox.setText(_translate("MainWindow", "开始工作日期"))
        self.employeeSearchSDateComboBox.setItemText(0, _translate("MainWindow", "晚于"))
        self.employeeSearchSDateComboBox.setItemText(1, _translate("MainWindow", "不早于"))
        self.employeeSearchSDateComboBox.setItemText(2, _translate("MainWindow", "是"))
        self.employeeSearchSDateComboBox.setItemText(3, _translate("MainWindow", "不晚于"))
        self.employeeSearchSDateComboBox.setItemText(4, _translate("MainWindow", "早于"))
        self.employeeSearchSDateComboBox.setItemText(5, _translate("MainWindow", "不是"))
        self.employeeSearchSDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "员工管理"))
        self.customerEditGroupBox.setTitle(_translate("MainWindow", "管理"))
        self.customerIDLabel.setText(_translate("MainWindow", "身份证号："))
        self.customerSavePushButton.setText(_translate("MainWindow", "保存"))
        self.customerAlterPushButton.setText(_translate("MainWindow", "修改"))
        self.customerAbortPushButton.setText(_translate("MainWindow", "放弃"))
        self.customerAddPushButton.setText(_translate("MainWindow", "添加"))
        self.customerDeletePushButton.setText(_translate("MainWindow", "删除"))
        self.customerNameLabel.setText(_translate("MainWindow", "姓名："))
        self.customerTeleLabel.setText(_translate("MainWindow", "电话："))
        self.customerAddressLabel.setText(_translate("MainWindow", "地址："))
        self.contactNameLabel.setText(_translate("MainWindow", "联系人姓名："))
        self.contactTeleLabel.setText(_translate("MainWindow", "联系人电话："))
        self.contactEmailLabel.setText(_translate("MainWindow", "联系人电子邮件地址："))
        self.contactRelationshipLabel.setText(_translate("MainWindow", "与客户关系："))
        self.customerSearchGroupBox.setTitle(_translate("MainWindow", "查找"))
        self.customerSearchPushButton.setText(_translate("MainWindow", "查找"))
        self.customerSearchCustomerIDCheckBox.setText(_translate("MainWindow", "身份证号"))
        self.customerSearchCustomerIDComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.customerSearchCustomerIDComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.customerSearchCustomerIDComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.customerSearchCustomerNameCheckBox.setText(_translate("MainWindow", "姓名"))
        self.customerSearchCustomerNameComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.customerSearchCustomerNameComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.customerSearchCustomerNameComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.customerSearchOtherInfoCheckBox.setText(_translate("MainWindow", "其他信息"))
        self.customerSearchOtherInfoComboBox.setCurrentText(_translate("MainWindow", "包含"))
        self.customerSearchOtherInfoComboBox.setItemText(0, _translate("MainWindow", "包含"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "客户管理"))
        self.accountEditGroupBox.setTitle(_translate("MainWindow", "管理"))
        self.accountIDLabel.setText(_translate("MainWindow", "账户号："))
        self.accountSavePushButton.setText(_translate("MainWindow", "保存"))
        self.accountAlterPushButton.setText(_translate("MainWindow", "修改"))
        self.accountAbortPushButton.setText(_translate("MainWindow", "放弃"))
        self.accountAddPushButton.setText(_translate("MainWindow", "添加"))
        self.accountDeletePushButton.setText(_translate("MainWindow", "删除"))
        self.accountCIDLabel.setText(_translate("MainWindow", "身份证号："))
        self.accountBIDLabel.setText(_translate("MainWindow", "支行号："))
        self.accountCNLabel.setText(_translate("MainWindow", "姓名："))
        self.accountBalanceLabel.setText(_translate("MainWindow", "余额："))
        self.accountIRateLabel.setText(_translate("MainWindow", "利率："))
        self.accountODateLabel.setText(_translate("MainWindow", "开户日期："))
        self.accountLDateLabel.setText(_translate("MainWindow", "最近访问日期："))
        self.accountBalanceCreditLabel.setText(_translate("MainWindow", "额度："))
        self.accountTypeLabel.setText(_translate("MainWindow", "账户类型："))
        self.accountTypeComboBox.setItemText(0, _translate("MainWindow", "存款"))
        self.accountTypeComboBox.setItemText(1, _translate("MainWindow", "支票"))
        self.accountODateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.accountLastDateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.accountEIDLabel.setText(_translate("MainWindow", "负责人工号："))
        self.accountENLabel.setText(_translate("MainWindow", "负责人姓名："))
        self.accountCNYLabel.setText(_translate("MainWindow", "币种："))
        self.accountBNLabel.setText(_translate("MainWindow", "支行名："))
        self.accountSearchGroupBox.setTitle(_translate("MainWindow", "查找"))
        self.accountSearchPushButton.setText(_translate("MainWindow", "查找"))
        self.accountSearchRangeLabel.setText(_translate("MainWindow", "范围："))
        self.accountSearchRangeComboBox.setItemText(0, _translate("MainWindow", "全部"))
        self.accountSearchRangeComboBox.setItemText(1, _translate("MainWindow", "上一次结果"))
        self.accountSearchCheckBox.setText(_translate("MainWindow", "字段："))
        self.accountSearchOpComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.accountSearchOpComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.accountSearchOpComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.accountSearchColComboBox.setItemText(0, _translate("MainWindow", "账户号"))
        self.accountSearchColComboBox.setItemText(1, _translate("MainWindow", "账户类型"))
        self.accountSearchColComboBox.setItemText(2, _translate("MainWindow", "支行号"))
        self.accountSearchColComboBox.setItemText(3, _translate("MainWindow", "支行名"))
        self.accountSearchColComboBox.setItemText(4, _translate("MainWindow", "身份证号"))
        self.accountSearchColComboBox.setItemText(5, _translate("MainWindow", "姓名"))
        self.accountSearchColComboBox.setItemText(6, _translate("MainWindow", "余额"))
        self.accountSearchColComboBox.setItemText(7, _translate("MainWindow", "额度"))
        self.accountSearchColComboBox.setItemText(8, _translate("MainWindow", "利率"))
        self.accountSearchColComboBox.setItemText(9, _translate("MainWindow", "开户日期"))
        self.accountSearchColComboBox.setItemText(10, _translate("MainWindow", "最近访问日期"))
        self.accountSearchColComboBox.setItemText(11, _translate("MainWindow", "负责人工号"))
        self.accountSearchColComboBox.setItemText(12, _translate("MainWindow", "负责人姓名"))
        self.accountSearchColComboBox.setItemText(13, _translate("MainWindow", "币种"))
        self.label.setText(_translate("MainWindow", "日期格式：yyyy-MM-dd"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "账户管理"))
        self.accountSearchGroupBox_2.setTitle(_translate("MainWindow", "查找"))
        self.accountSearchPushButton_2.setText(_translate("MainWindow", "查找"))
        self.accountSearchRangeLabel_2.setText(_translate("MainWindow", "范围："))
        self.accountSearchRangeComboBox_2.setItemText(0, _translate("MainWindow", "全部"))
        self.accountSearchRangeComboBox_2.setItemText(1, _translate("MainWindow", "上一次结果"))
        self.accountSearchCheckBox_2.setText(_translate("MainWindow", "字段："))
        self.accountSearchOpComboBox_2.setItemText(0, _translate("MainWindow", "等于"))
        self.accountSearchOpComboBox_2.setItemText(1, _translate("MainWindow", "不等于"))
        self.accountSearchOpComboBox_2.setItemText(2, _translate("MainWindow", "包含"))
        self.accountSearchColComboBox_2.setItemText(0, _translate("MainWindow", "账户号"))
        self.accountSearchColComboBox_2.setItemText(1, _translate("MainWindow", "账户类型"))
        self.accountSearchColComboBox_2.setItemText(2, _translate("MainWindow", "支行号"))
        self.accountSearchColComboBox_2.setItemText(3, _translate("MainWindow", "支行名"))
        self.accountSearchColComboBox_2.setItemText(4, _translate("MainWindow", "身份证号"))
        self.accountSearchColComboBox_2.setItemText(5, _translate("MainWindow", "姓名"))
        self.accountSearchColComboBox_2.setItemText(6, _translate("MainWindow", "余额"))
        self.accountSearchColComboBox_2.setItemText(7, _translate("MainWindow", "额度"))
        self.accountSearchColComboBox_2.setItemText(8, _translate("MainWindow", "利率"))
        self.accountSearchColComboBox_2.setItemText(9, _translate("MainWindow", "开户日期"))
        self.accountSearchColComboBox_2.setItemText(10, _translate("MainWindow", "最近访问日期"))
        self.accountSearchColComboBox_2.setItemText(11, _translate("MainWindow", "负责人工号"))
        self.accountSearchColComboBox_2.setItemText(12, _translate("MainWindow", "负责人姓名"))
        self.accountSearchColComboBox_2.setItemText(13, _translate("MainWindow", "币种"))
        self.label_2.setText(_translate("MainWindow", "日期格式：yyyy-MM-dd"))
        self.groupBox.setTitle(_translate("MainWindow", "管理"))
        self.accountDeletePushButton_2.setText(_translate("MainWindow", "删除"))
        self.accountAddPushButton_2.setText(_translate("MainWindow", "添加"))
        self.accountSavePushButton_2.setText(_translate("MainWindow", "保存"))
        self.accountAbortPushButton_2.setText(_translate("MainWindow", "放弃"))
        self.label_3.setText(_translate("MainWindow", "贷款号："))
        self.label_4.setText(_translate("MainWindow", "姓名："))
        self.label_5.setText(_translate("MainWindow", "身份证号："))
        self.label_6.setText(_translate("MainWindow", "支行名："))
        self.label_7.setText(_translate("MainWindow", "支行号："))
        self.label_8.setText(_translate("MainWindow", "负责员工："))
        self.label_9.setText(_translate("MainWindow", "负责人身份证号："))
        self.label_10.setText(_translate("MainWindow", "状态："))
        self.label_11.setText(_translate("MainWindow", "发放情况："))
        self.label_12.setText(_translate("MainWindow", "总金额："))
        self.label_13.setText(_translate("MainWindow", "发放贷款："))
        self.spinBox.setSuffix(_translate("MainWindow", "元"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "贷款管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "业务统计"))

