# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bank.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(688, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 671, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.branchTableView = QtWidgets.QTableView(self.tab)
        self.branchTableView.setGeometry(QtCore.QRect(10, 10, 391, 341))
        self.branchTableView.setObjectName("branchTableView")
        self.branchEditGroupBox = QtWidgets.QGroupBox(self.tab)
        self.branchEditGroupBox.setGeometry(QtCore.QRect(410, 10, 241, 341))
        self.branchEditGroupBox.setObjectName("branchEditGroupBox")
        self.branchIDLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchIDLabel.setGeometry(QtCore.QRect(20, 75, 54, 12))
        self.branchIDLabel.setObjectName("branchIDLabel")
        self.branchIDLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchIDLineEdit.setEnabled(False)
        self.branchIDLineEdit.setGeometry(QtCore.QRect(100, 70, 121, 21))
        self.branchIDLineEdit.setObjectName("branchIDLineEdit")
        self.saveBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.saveBranchPushButton.setGeometry(QtCore.QRect(150, 300, 75, 23))
        self.saveBranchPushButton.setObjectName("saveBranchPushButton")
        self.editBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.editBranchPushButton.setGeometry(QtCore.QRect(90, 20, 61, 23))
        self.editBranchPushButton.setObjectName("editBranchPushButton")
        self.abortBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.abortBranchPushButton.setGeometry(QtCore.QRect(50, 300, 75, 23))
        self.abortBranchPushButton.setObjectName("abortBranchPushButton")
        self.addBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.addBranchPushButton.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.addBranchPushButton.setObjectName("addBranchPushButton")
        self.deleteBranchPushButton = QtWidgets.QPushButton(self.branchEditGroupBox)
        self.deleteBranchPushButton.setGeometry(QtCore.QRect(170, 20, 61, 23))
        self.deleteBranchPushButton.setObjectName("deleteBranchPushButton")
        self.branchAssetsLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchAssetsLabel.setGeometry(QtCore.QRect(20, 230, 54, 12))
        self.branchAssetsLabel.setObjectName("branchAssetsLabel")
        self.branchAsertLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchAsertLineEdit.setEnabled(False)
        self.branchAsertLineEdit.setGeometry(QtCore.QRect(20, 250, 201, 20))
        self.branchAsertLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.branchAsertLineEdit.setObjectName("branchAsertLineEdit")
        self.branchNameLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchNameLineEdit.setEnabled(False)
        self.branchNameLineEdit.setGeometry(QtCore.QRect(20, 140, 201, 20))
        self.branchNameLineEdit.setObjectName("branchNameLineEdit")
        self.branchNameLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchNameLabel.setGeometry(QtCore.QRect(20, 120, 54, 12))
        self.branchNameLabel.setObjectName("branchNameLabel")
        self.branchCityLabel = QtWidgets.QLabel(self.branchEditGroupBox)
        self.branchCityLabel.setGeometry(QtCore.QRect(20, 195, 54, 12))
        self.branchCityLabel.setObjectName("branchCityLabel")
        self.branchCityLineEdit = QtWidgets.QLineEdit(self.branchEditGroupBox)
        self.branchCityLineEdit.setEnabled(False)
        self.branchCityLineEdit.setGeometry(QtCore.QRect(100, 190, 121, 20))
        self.branchCityLineEdit.setObjectName("branchCityLineEdit")
        self.branchSearchGroupBox = QtWidgets.QGroupBox(self.tab)
        self.branchSearchGroupBox.setGeometry(QtCore.QRect(10, 360, 641, 211))
        self.branchSearchGroupBox.setObjectName("branchSearchGroupBox")
        self.branchSearchPushButton = QtWidgets.QPushButton(self.branchSearchGroupBox)
        self.branchSearchPushButton.setGeometry(QtCore.QRect(500, 160, 101, 31))
        self.branchSearchPushButton.setObjectName("branchSearchPushButton")
        self.branchSearchBranchIDCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchBranchIDCheckBox.setGeometry(QtCore.QRect(20, 75, 61, 16))
        self.branchSearchBranchIDCheckBox.setObjectName("branchSearchBranchIDCheckBox")
        self.branchSearchBranchIDLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchBranchIDLineEdit.setEnabled(False)
        self.branchSearchBranchIDLineEdit.setGeometry(QtCore.QRect(200, 70, 101, 20))
        self.branchSearchBranchIDLineEdit.setObjectName("branchSearchBranchIDLineEdit")
        self.branchSearchBranchIDComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchBranchIDComboBox.setEnabled(False)
        self.branchSearchBranchIDComboBox.setGeometry(QtCore.QRect(90, 70, 91, 22))
        self.branchSearchBranchIDComboBox.setObjectName("branchSearchBranchIDComboBox")
        self.branchSearchBranchIDComboBox.addItem("")
        self.branchSearchBranchIDComboBox.addItem("")
        self.branchSearchBranchIDComboBox.addItem("")
        self.branchSearchRangeLabel = QtWidgets.QLabel(self.branchSearchGroupBox)
        self.branchSearchRangeLabel.setGeometry(QtCore.QRect(30, 25, 36, 12))
        self.branchSearchRangeLabel.setObjectName("branchSearchRangeLabel")
        self.branchSearchRangeComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchRangeComboBox.setGeometry(QtCore.QRect(110, 20, 111, 22))
        self.branchSearchRangeComboBox.setObjectName("branchSearchRangeComboBox")
        self.branchSearchRangeComboBox.addItem("")
        self.branchSearchRangeComboBox.addItem("")
        self.branchSearchBranchNameCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchBranchNameCheckBox.setGeometry(QtCore.QRect(20, 115, 71, 16))
        self.branchSearchBranchNameCheckBox.setObjectName("branchSearchBranchNameCheckBox")
        self.branchSearchBranchNameComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchBranchNameComboBox.setEnabled(False)
        self.branchSearchBranchNameComboBox.setGeometry(QtCore.QRect(88, 110, 91, 22))
        self.branchSearchBranchNameComboBox.setObjectName("branchSearchBranchNameComboBox")
        self.branchSearchBranchNameComboBox.addItem("")
        self.branchSearchBranchNameComboBox.addItem("")
        self.branchSearchBranchNameComboBox.addItem("")
        self.branchSearchBranchNameLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchBranchNameLineEdit.setEnabled(False)
        self.branchSearchBranchNameLineEdit.setGeometry(QtCore.QRect(200, 110, 101, 20))
        self.branchSearchBranchNameLineEdit.setObjectName("branchSearchBranchNameLineEdit")
        self.branchSearchCityCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchCityCheckBox.setGeometry(QtCore.QRect(330, 115, 51, 16))
        self.branchSearchCityCheckBox.setObjectName("branchSearchCityCheckBox")
        self.branchSearchCityComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchCityComboBox.setEnabled(False)
        self.branchSearchCityComboBox.setGeometry(QtCore.QRect(388, 110, 91, 22))
        self.branchSearchCityComboBox.setObjectName("branchSearchCityComboBox")
        self.branchSearchCityComboBox.addItem("")
        self.branchSearchCityComboBox.addItem("")
        self.branchSearchCityComboBox.addItem("")
        self.branchSearchCityLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchCityLineEdit.setEnabled(False)
        self.branchSearchCityLineEdit.setGeometry(QtCore.QRect(500, 110, 101, 20))
        self.branchSearchCityLineEdit.setObjectName("branchSearchCityLineEdit")
        self.branchSearchAssetComboBox = QtWidgets.QComboBox(self.branchSearchGroupBox)
        self.branchSearchAssetComboBox.setEnabled(False)
        self.branchSearchAssetComboBox.setGeometry(QtCore.QRect(388, 70, 91, 22))
        self.branchSearchAssetComboBox.setObjectName("branchSearchAssetComboBox")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetComboBox.addItem("")
        self.branchSearchAssetCheckBox = QtWidgets.QCheckBox(self.branchSearchGroupBox)
        self.branchSearchAssetCheckBox.setGeometry(QtCore.QRect(330, 75, 71, 16))
        self.branchSearchAssetCheckBox.setObjectName("branchSearchAssetCheckBox")
        self.branchSearchAssetLineEdit = QtWidgets.QLineEdit(self.branchSearchGroupBox)
        self.branchSearchAssetLineEdit.setEnabled(False)
        self.branchSearchAssetLineEdit.setGeometry(QtCore.QRect(500, 70, 101, 20))
        self.branchSearchAssetLineEdit.setObjectName("branchSearchAssetLineEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "银行管理系统"))
        self.branchEditGroupBox.setTitle(_translate("MainWindow", "编辑"))
        self.branchIDLabel.setText(_translate("MainWindow", "支行编号："))
        self.saveBranchPushButton.setText(_translate("MainWindow", "保存"))
        self.editBranchPushButton.setText(_translate("MainWindow", "修改"))
        self.abortBranchPushButton.setText(_translate("MainWindow", "放弃"))
        self.addBranchPushButton.setText(_translate("MainWindow", "添加"))
        self.deleteBranchPushButton.setText(_translate("MainWindow", "删除"))
        self.branchAssetsLabel.setText(_translate("MainWindow", "支行资产："))
        self.branchNameLabel.setText(_translate("MainWindow", "支行名："))
        self.branchCityLabel.setText(_translate("MainWindow", "城市："))
        self.branchSearchGroupBox.setTitle(_translate("MainWindow", "查找"))
        self.branchSearchPushButton.setText(_translate("MainWindow", "查找"))
        self.branchSearchBranchIDCheckBox.setText(_translate("MainWindow", "支行号"))
        self.branchSearchBranchIDComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.branchSearchBranchIDComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.branchSearchBranchIDComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.branchSearchRangeLabel.setText(_translate("MainWindow", "范围："))
        self.branchSearchRangeComboBox.setItemText(0, _translate("MainWindow", "全部"))
        self.branchSearchRangeComboBox.setItemText(1, _translate("MainWindow", "上一次结果"))
        self.branchSearchBranchNameCheckBox.setText(_translate("MainWindow", "支行名"))
        self.branchSearchBranchNameComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.branchSearchBranchNameComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.branchSearchBranchNameComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.branchSearchCityCheckBox.setText(_translate("MainWindow", "城市"))
        self.branchSearchCityComboBox.setItemText(0, _translate("MainWindow", "等于"))
        self.branchSearchCityComboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.branchSearchCityComboBox.setItemText(2, _translate("MainWindow", "包含"))
        self.branchSearchAssetComboBox.setItemText(0, _translate("MainWindow", "大于"))
        self.branchSearchAssetComboBox.setItemText(1, _translate("MainWindow", "大于等于"))
        self.branchSearchAssetComboBox.setItemText(2, _translate("MainWindow", "等于"))
        self.branchSearchAssetComboBox.setItemText(3, _translate("MainWindow", "小于等于"))
        self.branchSearchAssetComboBox.setItemText(4, _translate("MainWindow", "小于"))
        self.branchSearchAssetComboBox.setItemText(5, _translate("MainWindow", "不等于"))
        self.branchSearchAssetCheckBox.setText(_translate("MainWindow", "资产"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "支行管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "员工管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "客户管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "账户管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "贷款管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "业务统计"))

